### ISSUE TITLE
Hangouts scree nsharing not working

### ISSUE THREAD

**Issue by Ezerbeth** [gliaskos/freebsd-chromium#138]
Hello,

Hangouts screen sharing doesn't work due to the compile option
`enable_hangout_services_extension=true`
missing from the Makefile and no option available.

Could this be added so that default behavior is to have working screen sharing?

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1389708

Thanks

**Comment by cpu82** [comment]
Hi @Ezerbeth:

I have enabled the Hangout extension in the `Makefile`

https://github.com/cpu82/freebsd-chromium/blob/master/www/chromium/Makefile#L107

**Comment by Ezerbeth** [comment]
Thanks!
