### ISSUE TITLE
"End" key not working

### ISSUE THREAD

**Issue by lapo-luchini** [gliaskos/freebsd-chromium#172]
The "End" key does nothing at all, in any Chromium page/tab/extension.
(it does work in any other software, included VSCode, which has much code in common)
This started happening with a global `pkg upgrade` in the past 2-3 weeks.
Right now I'm using `chromium-79.0.3945.130`.

**Comment by appcrash** [comment]
Same issue, end key works on all application but chromium,version: 79.0.3945.130 (Official Build) (64-bit), 12.1-RELEASE-p3

**Comment by mwolf-rw** [comment]
Can you re-test with chromium 80 or 81? Those don't seem to have this issue (as well as being a bit more stable in general).

**Comment by appcrash** [comment]
after upgrading to 80 end key works

**Comment by lapo-luchini** [comment]
It was solved to me already by recent Xorg upgrade using evdev, rather than upgrading Chrome itself.
I can't re-test this on recent Chrome at the moment (because Covid19 has me far from that PC) but I guess this can be closed.
