### ISSUE TITLE
sync is not working

### ISSUE THREAD

**Issue by GuillaumeBibaut** [gliaskos/freebsd-chromium#178]
Everything is in the title.

Installed chromium, connected with a google account.
Sync internals tells that the last sync happened `5,114 hours, 44 minutes ago`.

`Request Start` button does nothing
`Trigger GetUpdates` button does nothing.

**Comment by lapo-luchini** [comment]
I wonder if this log is related:

`ERROR:browser_dm_token_storage_linux.cc(100)] Error: /etc/machine-id contains 0 characters (32 were expected).`

**Comment by mwolf-rw** [comment]
Should be working again in version 83.0.4103.106

**Comment by GuillaumeBibaut** [comment]
Working great now, TY!

**Comment by lapo-luchini** [comment]
I got an [error in sync](chrome://sync/):
`Error: MergeSyncData@../../components/password_manager/core/browser/sync/password_sync_bridge.cc:361, datatype error was encountered: Failed to load entries from password store. Encryption service failure.`
I solved that by removing local store (it triggered a full download from cloud, which worked fine):
`rm ~/.config/chromium/Profile\ 3/Login\ Data`.
