### ISSUE TITLE
Plugin installation seems to be broken and high idle CPU

### ISSUE THREAD

**Issue by teran-mckinney** [gliaskos/freebsd-chromium#23]
Hi everyone,

After the latest patches, I installed the update. I cannot install Chrome plugins now (at least the Okta one). I did have one crash on the plugin install page. Also, like before, idle CPU is around 100% even though the browser is generally responsive.

Are there any test cases around Chrome? I'm interested in building out a platform to test it, or at least some test cases where Chrome navigates and gets checked for crashes, ideally put into Travis or something like it.

Lastly, can you sign up this project for https://tip4commit.com/ ? I'd like to sponsor the project.

Thank you,
Teran

**Comment by rene0** [comment]
I haven't seen the CPU filling up, so maybe it depends on the page? I currently have 32 tabs open on an old Intel T6600 CPU (2.2 GHz, dualcore, amd64). This is on PC-BSD 11 from July 2015.

About testing: upstream has extensive tests, see https://build.chromium.org/ . Each change is also build-tested before it gets pushed. This is done for all supported platforms. Unfortunately *BSD are not part of that. Making it supported takes political persuasion I guess...

**Comment by teran-mckinney** [comment]
I haven't seen this either for quite a while. I'll go ahead and close this out for now.

Thank you!
