### ISSUE TITLE
44.0.2403.125 does not launch a window

### ISSUE THREAD

**Issue by teran-mckinney** [gliaskos/freebsd-chromium#27]
Hi,

44.0.2403.104 was working pretty well. Almost back to normal with downloads working, plugin installation, and the occasional Aw, snap! crash. 44.0.2403.125 won't even pull up a window for me. If I run chromium it forks, returns 0, and spins and spins doing nothing (_sysctl in truss -fp), never coming up. This is on 10.1-RELEASE. I went back to 104 and it came up.

Can anyone else confirm this behavior?

Thank you,
Teran

**Comment by thmzlt** [comment]
Same here.

**Comment by teran-mckinney** [comment]
.130 also behaves the same way. I'm sticking with .107 (I think I meant .107 above) for now.

**Comment by jhofmann** [comment]
I can confirm the problem with .130 and 10.1-RELEASE.

**Comment by cpu82** [comment]
@jhofmann currently, chrome works on 10.2-RELEASE.

**Comment by teran-mckinney** [comment]
I upgraded to 10.2-RELEASE and it fixed it for me.

**Comment by jhofmann** [comment]
I can confirm that it works in10.2-RELEASE for me too, thanks!

**Comment by teran-mckinney** [comment]
I can close this out if you guys want. Not sure if we want to maintain 10.1-RELEASE compatibility or not, but at least it's a good upgrade/workaround.

**Comment by teran-mckinney** [comment]
Closing as it works on 10.2. May have still been fixed in later versions; I have not tested.
