### ISSUE TITLE
chromium 45 build fails on 9.3

### ISSUE THREAD

**Issue by rene0** [gliaskos/freebsd-chromium#33]
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.h264chro): In function `ff_h264chroma_init':
h264chroma.c:(.text.unlikely.ff_h264chroma_init+0xb7): undefined reference to `ff_h264chroma_init_x86'
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.h264dsp.): In function `ff_h264dsp_init':
h264dsp.c:(.text.unlikely.ff_h264dsp_init+0x1fa): undefined reference to `ff_h264dsp_init_x86'
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.h264qpel): In function `ff_h264qpel_init':
h264qpel.c:(.text.unlikely.ff_h264qpel_init+0x18b6): undefined reference to `ff_h264qpel_init_x86'
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.autorena): In function `ff_mpadsp_init':
autorename_libavcodec_mpegaudiodsp.c:(.text.unlikely.ff_mpadsp_init+0x77): undefined reference to `ff_mpadsp_init_x86'
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.dct.o): In function `ff_dct_init':
dct.c:(.text.unlikely.ff_dct_init+0x1b5): undefined reference to `ff_dct_init_x86'
obj/third_party/ffmpeg/libffmpeg.a(ffmpeg.sbrdsp.o): In function `ff_sbrdsp_init':
sbrdsp.c:(.text.unlikely.ff_sbrdsp_init+0x94): undefined reference to `ff_sbrdsp_init_x86'
collect2: error: ld returned 1 exit status

**Comment by cpu82** [comment]
Is @LeFroid working on this?

**Comment by LeFroid** [comment]
I'll write up a patch for this ASAP. Had a similar issue on 10-STABLE but I figured my fix would've worked for other versions as well

**Comment by rene0** [comment]
OK thanks all :)
