### ISSUE TITLE
Many pages often "hang"

### ISSUE THREAD

**Issue by lapo-luchini** [gliaskos/freebsd-chromium#63]
It's been a long time since the last «Aw, snap» error, but lately I'm having a lots of problems loading a few websites (e.g. Facebook, Google Plus, I guess it might be something regarding intensive AJAX usage, but also happens on random "light" pages, less frequently); the page never loads (and the icon in the tab continues spinning) or the page loads but then stops after a very small time (doesn't click on links, doesn't scroll).

I'm using version 52.0.2743.116 (64-bit) as installed with `pkg install chromium` on `FreeBSD 10.3-RELEASE-p4`.

Happens to anyone else or should I check my installation more?

PS: I added `127.0.0.2 www.kickstarter.com` to `/etc/hosts` to avoid those crashes.

**Comment by teran-mckinney** [comment]
I see that, too. I get the hangs quite often. Wonder if they are related.

**Comment by anvio** [comment]
I am having the same issue with version 52.0.2743.116 (64-bit) on FreeBSD 11.0-RELEASE-p1.

**Comment by Shoen** [comment]
same issue. deleting cached items and reopening the tab on the same url solves the issue for that session but on each new session it comes back

**Comment by refferer** [comment]
I try version 55.0.2883.87 from cpu82.
For me, beginning with 52, chromium hang in 90% of cases for own pages (chrome://) and extensions.
Now ~10-20%.
Chromium became usable, but the problem still remains.

**Comment by refferer** [comment]
And if I close chromium with hang, it leaves process:
ps auxd | grep chrome
user  56853  0.0  2.3 944984 93680  7  IN   16:49   0:00.35 chrome: HTMLParserThread (chrome)

**Comment by marcusreid** [comment]
I get the same problem, and frequently enough to make the browser nearly unusable. Is there any pattern to who is seeing it?

$ uname -a
FreeBSD sol 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

[    13.438] (II) NVIDIA dlloader X Driver  378.09  Sat Jan 14 21:42:42 PST 2017
[    13.438] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs

**Comment by mrmarbury** [comment]
Same problem here. FreeBSD 11.0-RELEASE-p8, chromium-56.0.2924.87_1

It is really unnerving, if that happens when you try to pay online

**Comment by cpu82** [comment]
Have you try to disable V8 cache?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212812#c24

**Comment by fjerhammer** [comment]
Unfortunately, disabling the V8 cache did not change anything for me.

My workaround is to simply open a new tab and copy the URL over whenever it happens. In most cases Chromium will be able to render the page after the second or third attempt.
Kickstarter.com has never been a problem for me, but facebook.com hangs about 50% of the time.

I am using chromium-56.0.2924.87_2 on 11.0-RELEASE-p8 (CPUTYPE?=haswell) with the proprietary NVIDIA driver.

**Comment by ehasting** [comment]
same problem here:
FreeBSD drno.int.synergysky.com 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
$ chrome --version
Chromium 58.0.3029.110 
(--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 4400
CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (2693.82-MHz K8-class CPU)

however, i get the same problem on my other computer too (same freebsd ver, another intel chip)

**Comment by fuzxxl** [comment]
Same problem here. Worse, not only does the tab hang but rather all tabs in the same tab group as indicated by Chromium's task manager. Could this be related to the FreeBSD network stack?

**Comment by eriknstr** [comment]
I've been having this problem for a very long time as well.

**Comment by cpu82** [comment]
Please try the following patch [1] attached to PR211036.

Until now I have not had any problem. Let me know if it works.

[1] https://bz-attachments.freebsd.org/attachment.cgi?id=184117

**Comment by fuzxxl** [comment]
Disabling V8 cache reduced the problem massively; now tabs only ocassionally hang and only one tab hangs at a time. Plus you can actually close them now.

**Comment by martinkovacik** [comment]
Same problem with Chromium 59.0.3071.115_2 on FreeBSD 11.1-RELEASE

**Comment by ehasting** [comment]
How do i turn off v8-caching ?
Can anyone else confirm if the patch is working or not?

**Comment by fuzxxl** [comment]
@ehasting  Try chrome:flags. I have not tried the flag, but turning off v8-caching reduced the severity of this bug to rare harmless occurrences than only affect a single tab at a time.

**Comment by ehasting** [comment]
i have now tried with v8-caching disabled for a while, and i can now use chromium.. i have had zero problem after changing the flag!

however, i dont have time to learn how to build chromium right now, but if anyone have made a release with the suggested patch - i am willing to try it out!

**Comment by stefanclayster** [comment]
Disabling v8 caching does not work for me. Luckily the biggest problem is facebook where i can reproduce the.

**Comment by mdsn** [comment]
Can confirm this issue happens all day every day, without a clear reason and without consistency, on sites like jira, gmail, reddit.

**Comment by cpu82** [comment]
It seems that mounting ~/.cache/chromium as tmpfs fixes hanging tabs issue.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226793

**Comment by lapo-luchini** [comment]
Since I added `net.local.stream.recvspace=16384` as suggested in [PR 212812](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212812) (and then upgraded to latest 12.x) I don't remember any more occurrence, I'd say this can be closed. (yay!)
