### ISSUE TITLE
No sound in chrome

### ISSUE THREAD

**Issue by avr39-ripe** [gliaskos/freebsd-chromium#71]
There is no sound in chrome from this repo (recent build of chromium-54.0.2840.100) on freebsd-current
Chrome itself works fine, much smoother than 51.x from ports, but no sound on youtube and other sites. Can provide additional info on request.

**Comment by cpu82** [comment]
Hi,

You need to enable `ALSA` or `PULSEADIO` via `make config` to select one of them.

We will re-add back one of them to `DEFAULT_OPTIONS` when we agree on which one.

**Comment by avr39-ripe** [comment]
Oh! thanks for quick answer! And can I somehow build just missing part of chrome instead full rebuild?

**Comment by cpu82** [comment]
You need to rebuild again `www/chromium`.

**Comment by avr39-ripe** [comment]
Reconfigure, rebuild missing parts reinstall and :) here comes the party! ;) thanks, problem fixed!
